# Generated by Django 3.2.18 on 2023-02-23 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppin_market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='OrderID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_of_products', to='shoppin_market.orders'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_in_order', to='shoppin_market.product'),
        ),
    ]
